### ISSUE TITLE
模糊音配置中有en => eng, in => ing，eng => en, ing => in，没有an和ang

### ISSUE THREAD

**Issue by heqirong** [FydeOS/fydeRhythm#10]
模糊音配置中有en => eng, in => ing，eng => en, ing => in，没有an和ang

**Comment by fydeos-alex** [comment]
感谢你使用真文韵输入法，你可以通过编辑 RIME 配置文件实现自定义规则 an => ang / ang => an 。
你可以打开RIME编辑器在 root/build/ 下找到 (你使用的拼音方案，如：极光「aurora_pinyin」/ 雾凇「rime_ice」).schema.yaml 文件，搜索speller，在 speller:algebra: 下添加你想要的规则。
你可以添加
```
    - derive/([a])ng$/$1n/ # ang =>an
    - derive/([a])n$/$1ng/ # an => ang
```
保存后即可实现模糊音配置。
更多详细信息可以参考[这篇回答](https://github.com/FydeOS/fydeRhythm/issues/7#issuecomment-2009006820)和RIME[官方定制指南](https://github.com/rime/home/wiki/CustomizationGuide)
