### ISSUE TITLE
虚拟键盘宽度小于屏幕宽度

### ISSUE THREAD

**Issue by Chihsiao** [FydeOS/fydeRhythm#11]
![](https://github.com/FydeOS/fydeRhythm/assets/20290900/b9e2c8ae-4d38-4337-9487-2b4b03ab1995)

如图所示，虚拟键盘宽度小于屏幕宽度。

可能的复现过程：

1. 切换到 Tablet 模式；
2. 输入法切换成 US 输入法；
3. 将虚拟键盘切换成悬浮状态，改变大小和位置；
4. 输入法切换成真文韵输入法。
5. 输入法切换成 US 输入法；
6. 取消虚拟键盘悬浮状态；
7. 重启。

**Comment by alphato-o** [comment]
这不是真文韵输入法所管辖的问题，是 FydeOS / openFyde 屏幕键盘可能带来的瑕疵。

另，经测试，在 FydeOS v19 中已无法复现。
