### ISSUE TITLE
Chrome OS flex

### ISSUE THREAD

**Issue by MSJXMG** [FydeOS/fydeRhythm#12]
请问Chrome OS flex可以安装吗？，谢谢。

**Comment by fydeos-alex** [comment]
非常抱歉，因为谷歌最新版本的限制，Chrome OS将不支持真文韵输入法的使用。但你可以在FydeOS上使用。🤗

**Comment by zanjie1999** [comment]
先安装再升级亲测可用，比如113升级123

**Comment by nxy1999** [comment]
> 非常抱歉，因为谷歌最新版本的限制，Chrome OS将不支持真文韵输入法的使用。但你可以在FydeOS上使用。🤗

以后也不会支持了吗

**Comment by alphato-o** [comment]
以后的事情很难预测，Google 的态度也不是很明确

**Comment by nxy1999** [comment]
> 以后的事情很难预测，Google 的态度也不是很明确

目前还可以在系统设置里选择真文韵输入法，正常使用，挺好的。
