### ISSUE TITLE
更新到 2.1.2 版本 chromeOS M129 无法唤起屏幕键盘

### ISSUE THREAD

**Issue by gitiy1** [FydeOS/fydeRhythm#13]
首先还是感谢 2.1.2 的新特性以及与 Android Linux 子系统的性能改进，确实流畅丝滑了很多！

更新至 2.1.2 版本使用 ChromeOS M129 无法唤起屏幕键盘，在平板模式下使用有问题

**Comment by Lorde627** [comment]
由于 ChromeOS 系统的限制，真文韵输入法无法在 ChromeOS 中唤起屏幕键盘。
