### ISSUE TITLE
[Feature Request] 增加自定义方案的功能

### ISSUE THREAD

**Issue by GoodbyeNJN** [FydeOS/fydeRhythm#2]
目前无法加载其他方案，也无法在编辑页面中创建文件来实现自定义方案。是否考虑开放自定义方案？

**Comment by suochenxi** [comment]
我也遇到了这个问题，当前支持编辑已有配置文件，只能在现有方案的基础上小修小改，无法新增“自定义方案等”。

**Comment by xjjx-art** [comment]
十分支持。不知道为什么不开放自定义。开放了自定义输入方案，可以添加自己的方案，主系统以及子系统，一个输入法就完全覆盖了。Rime 的特点就是自定义码表啊。目前主系统这个虽然基本够用，但繁简切换不方便，俄文、日文等无法使用自定义的输入方案。在 Debian 或 Arch 子系统中，为了使用自定义方案，还得重新安装 fcitx5-rime，在 Arch 子系统中始终未能成功激活 fcitx5...

**Comment by alphato-o** [comment]
released in 2.1.2

**Comment by FEI352** [comment]
> released in 2.1.2

这个功能过于抽象，很多人没有弄明白，有没有简单易懂的教程？
