### ISSUE TITLE
真文韵输入法使用小鹤双拼时如何启用模糊音【请你喝一杯咖啡寻求帮助】

### ISSUE THREAD

**Issue by NJYZ-96** [FydeOS/fydeRhythm#7]
真文韵输入法使用小鹤双拼时如何启用模糊音【请你喝一杯咖啡寻求帮助】

Q：是否在社区搜索了相关问题

已查看社区和官方帮助文档，没有找到类似的issue

2. 详细叙述

(1) 具体问题

A：我是小鹤双拼+模糊音用户，很高兴fydeos团队的真文韵输入法能够使用小鹤双拼了，但由于南方人对于前后鼻音韵母啥的实在分不清，所以模糊音也是刚需。

使用真文韵输入法的双拼方案时设置里只有关于候选词数量的设置，没有模糊音的设置。

我在社区和官方帮助文档中没有找到相关的解决方案，真文韵输入法的双拼方案借用的是雾凇拼音 Rime 输入法，我在雾凇拼音和 Rime 输入法项目主页上看到是支持模糊音设置的，但由于本人没有编程基础，看不懂 Rime 输入法相关配置文件如何设置。

希望有相关大佬能帮忙完成我的需求，即小鹤双拼方案+所有常规的模糊音+候选词为9，其他的保持现状即可；

为了感谢大佬的帮助，愿意请你喝一杯咖啡，小小心意。

(2) 电脑具体配置和固件版本

FydeOS 版本:FydeOS for You-Surface Pro 5-16.1

**Comment by wenliang** [comment]
同求. :pray:

**Comment by fydeos-alex** [comment]
感谢你使用真文韵输入法，一个可行的解决办法是通过编辑 RIME 配置文件实现自定义规则。
你可以打开RIME编辑器在 root/build/ 下找到 double_pinyin_flypy.schema.yaml 文件，在目前版本633行（或搜索speller）的 speller:algebra: 下添加你想要的规则。
可选规则如下：
```
    - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh
    - derive/([aei])ng$/$1n/ # ang =>an, eng => en, ing => in
    - derive/([aei])n$/$1ng/ # an => ang, en => eng, in => ing
    - derive/^n/l/  # n => l
    - derive/^l/n/  # l => n 
```

具体配置位置可以看下图：
![image](https://github.com/FydeOS/fydeRhythm/assets/164128339/e27fe97d-1f38-440d-8691-750235873d37)
保存成功后即可以实现双拼模糊音。

注：这一方法有弊端如下：
- 当 Rime 软件升级时，也会升级各种设定档、预设输入方案。用户编辑过的文档会被覆写为更高版本，所做调整也便丢失了。
- 需要在更新后重复以上步骤恢复模糊音。

规则方案来自页面[【朙月拼音】模糊音定製模板](https://gist.github.com/lotem/2320943)

**Comment by NJYZ-96** [comment]
> 感谢你使用真文韵输入法，一个可行的解决办法是通过编辑 RIME 配置文件实现自定义规则。 你可以打开RIME编辑器在 root/build/ 下找到 double_pinyin_flypy.schema.yaml 文件，在目前版本633行（或搜索speller）的 speller:algebra: 下添加你想要的规则。 可选规则如下：
> 
> ```
>     - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
>     - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh
>     - derive/([aei])ng$/$1n/ # ang =>an, eng => en, ing => in
>     - derive/([aei])n$/$1ng/ # an => ang, en => eng, in => ing
>     - derive/^n/l/  # n => l
>     - derive/^l/n/  # l => n 
> ```
> 
> 具体配置位置可以看下图： ![image](https://private-user-images.githubusercontent.com/164128339/314415479-e27fe97d-1f38-440d-8691-750235873d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU4NDEsIm5iZiI6MTcxMTc0NTU0MSwicGF0aCI6Ii8xNjQxMjgzMzkvMzE0NDE1NDc5LWUyN2ZlOTdkLTFmMzgtNDQwZC04NjkxLTc1MDIzNTg3M2QzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQyMDUyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWI5OWE0ODRlYmU5ZjQzZmMyZWY4N2VjYjQyMmJiNzZiOTJmNWIxMGE1NWNjZjZmOTZiNTkwNzhkMjAxM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IXHuX6YlMCZrO07Er4RxlBYHh42l0jh7K-jr0FrDgM) 保存成功后即可以实现双拼模糊音。
> 
> 注：这一方法有弊端如下：
> 
> * 当 Rime 软件升级时，也会升级各种设定档、预设输入方案。用户编辑过的文档会被覆写为更高版本，所做调整也便丢失了。
> * 需要在更新后重复以上步骤恢复模糊音。
> 
> 规则方案来自页面[【朙月拼音】模糊音定製模板](https://gist.github.com/lotem/2320943)

很高兴得到你的帮助，但由于我的设备上一些兼容性问题，我目前放弃了使用FydeOS；但还是很感谢你的帮助，请你给我一个国内可用的收款方式，我很乐意请你喝一杯咖啡

**Comment by fydeos-alex** [comment]
很高兴能帮助到你，如果有更多兼容性问题，可以登陆FydeOS社区进行求助。我最近负责维护这个年久失修的项目，工作所在，咖啡就免了吧😊。

> > 感谢你使用真文韵输入法，一个可行的解决办法是通过编辑 RIME 配置文件实现自定义规则。 你可以打开RIME编辑器在 root/build/ 下找到 double_pinyin_flypy.schema.yaml 文件，在目前版本633行（或搜索speller）的 speller:algebra: 下添加你想要的规则。 可选规则如下：
> > ```
> >     - derive/^([zcs])h/$1/ # zh, ch, sh => z, c, s
> >     - derive/^([zcs])([^h])/$1h$2/ # z, c, s => zh, ch, sh
> >     - derive/([aei])ng$/$1n/ # ang =>an, eng => en, ing => in
> >     - derive/([aei])n$/$1ng/ # an => ang, en => eng, in => ing
> >     - derive/^n/l/  # n => l
> >     - derive/^l/n/  # l => n 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 具体配置位置可以看下图： ![image](https://private-user-images.githubusercontent.com/164128339/314415479-e27fe97d-1f38-440d-8691-750235873d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDU4NDEsIm5iZiI6MTcxMTc0NTU0MSwicGF0aCI6Ii8xNjQxMjgzMzkvMzE0NDE1NDc5LWUyN2ZlOTdkLTFmMzgtNDQwZC04NjkxLTc1MDIzNTg3M2QzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQyMDUyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWI5OWE0ODRlYmU5ZjQzZmMyZWY4N2VjYjQyMmJiNzZiOTJmNWIxMGE1NWNjZjZmOTZiNTkwNzhkMjAxM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9IXHuX6YlMCZrO07Er4RxlBYHh42l0jh7K-jr0FrDgM) 保存成功后即可以实现双拼模糊音。
> > 注：这一方法有弊端如下：
> > 
> > * 当 Rime 软件升级时，也会升级各种设定档、预设输入方案。用户编辑过的文档会被覆写为更高版本，所做调整也便丢失了。
> > * 需要在更新后重复以上步骤恢复模糊音。
> > 
> > 规则方案来自页面[【朙月拼音】模糊音定製模板](https://gist.github.com/lotem/2320943)
> 
> @fydeos-alex 很高兴得到你的帮助，但由于我的设备上一些兼容性问题，我目前放弃了使用FydeOS；但还是很感谢你的帮助，请你给我一个国内可用的收款方式，我很乐意请你喝一杯咖啡

很高兴能帮助到你，如果有更多兼容性问题，可以登陆FydeOS社区进行求助。我最近负责维护这个年久失修的项目，工作所在，咖啡就免了吧😊。

**Comment by wenliang** [comment]
非常感谢！ 我在 chromebook 上按照上面所说修改后可以使用模糊音。
现在输入中文就比较轻松了， 无需琢磨是否翘舌音。
