### ISSUE TITLE
Will fydeRhythm be incompatible with ChromeOS 119?

### ISSUE THREAD

**Issue by MondayCha** [FydeOS/fydeRhythm#8]
I would like to inquire about the compatibility of fydeRhythm with ChromeOS version 119. Recently, I came across a notification on the ChromeOS developer website (https://chromeos.dev/en/posts/chrome-input-ime-deprecation) regarding the deprecation of Chrome Input IME. 

As fydeRhythm relies on Chrome Input IME, I wanted to know if there are any plans or considerations to address this potential incompatibility issue.

Any information or insights regarding the impact of ChromeOS 119 on fydeRhythm's functionality would be greatly appreciated. Thank you!

**Comment by alphato-o** [comment]
Unfortunately, as a consequence of the deprecation, fydeRythem will cease to work in r119. We are still working on a possible workaround and actively liaising with Google for a more permanent resolution.

**Comment by MondayCha** [comment]
Thank you for your continuous efforts, fydeRhythm is such an excellent solution for double-pinyin input on ChromeOS 😭😭😭
